import Head from 'next/head'
import Image from 'next/image'
import Banner from '../Components/Banner/Banner'
import CompanyName from '../Components/CompanyName/CompanyName'
import Navbar from '../Components/Navbar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creative Agencies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <CompanyName />
      </main>
    </div>
  )
}
